version: '3'

services:
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: taxi

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181

    kafka:
        image: confluentinc/cp-kafka:latest
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper

    eurekaserver:
        build: ./eurekaServer
        ports:
            - 8761:8761

    gatewayclient:
        build: ./gatewayClient
        ports:
            - 8080:8080
        depends_on:
            - eurekaserver

    carservice:
        build: ./carService
        depends_on:
            - eurekaserver
            - db
#            - kafka

    tripservice:
        build: ./tripService
        depends_on:
            - eurekaserver
            - db
#            - kafka

    userservice:
        build: ./userService
        depends_on:
            - eurekaserver
            - db
