server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://db:5432/taxi
    driverClassName: org.postgresql.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
